services:
  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    depends_on:
      - etl    
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  etl:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: etl
    env_file:
      - .env
    volumes:
      - .:/app
    command: bash run_etl.sh
  
  streamlit:
    build:
      context: ./streamlit         
      dockerfile: Dockerfile       
    container_name: streamlit
    depends_on:
      - etl
      - db
    env_file:
      - .env                        
    ports:
      - "8501:8501"                 
    volumes:
      - ./streamlit:/app            
    command: streamlit run app.py 

volumes:
  db_data:
