version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  etl:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
    command: bash run_etl.sh
  
  streamlit:
    build:
      context: ./streamlit         
      dockerfile: Dockerfile       
    depends_on:
      - db
    env_file:
      - .env                        
    ports:
      - "8501:8501"                 
    volumes:
      - ./streamlit:/app            
    command: streamlit run app.py --server.address=0.0.0.0

volumes:
  db_data:
